travis:
  secure:
    BINSTAR_TOKEN: b0EbB+n7faJuf4DeZR4F5jSeQAWSd1CbPB3tLop+d9ySEZFN7ln6BeZXYgdZRKi8esUatT3CWX6yVcrMiB63uI0Ot4GXiqWfZ9goSWzt7B1E9LPmPaSLb5mePeO7ogU92p+9Hati08N5g8fy0Igxl6dPhRTzVzJmOs+O7IzL4o2a4KsGbBMj79KmRho3TBpf9BtKxSri9oTq2Yc8aKlKMvvQr2PY2WxblHSjcqcu/YbFIgjdBIdHcDPBsUILR3TLZXxS8+klJjavvx7gHzHXu56exbcgiRhvRN8FF25V2T/SEIwCaUCA3orBjZqHpoqQ3TAZOx+LlLpjQFCjNpqrAj/lBtKirz3zSbzqfxbSWd49Bt5u9yKXQCvHKhxQPNg205KsY5rfoPlyoVtHwOo/9gtVDOQB0aH3TpgkDJsn+XZBt82bQ1leN/RbV4fxd7rwSOOsHJnV4jCCdyE/aJAjLdMr1PdBylb0tTPQybBuvjkmufYP3ZlK50WwXPqroTphHR0FqH7Cktba/kdmUxCBneqFvNkEkds01It9AJVL+fHxb9JPPkbKm08V+wsV4A8rA6OxBApecuAZ863gq3UZo8B86fgb7b4/gGnAsxdYZPv15dXLF32MnT3o2HudbVdHYaIoy0a08rHgyBNbpzVnlf3KgmX3d7AlIZWEd4G0v3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
