travis:
  secure:
    BINSTAR_TOKEN: aIXiPguREh9PJYIXMSHp/lecT+D/L6zzTA8FT9LV/p6gxEsPLgK9AWCcAJZSetLWT+nUJAQMyVdqCwmG2BIA1rTLfO6l8GV2kU1VthcuIlfKSmpmQLesVIrARmuVExtXMxUyXkCwssM/k6and6nF/uTJcmAyq9DP7TrbrdvtUe5r3BIwrucK4gHdspX+nW3GDBlq10UawkI/MaZccrjNm7kQw94ZOYwNwZtHL5jekaoaCw1OLO3Mqe/EdW6RXXZog/8xPSNxNKf/wlMt4qQDQ1ZXkOKqK9PqKgm7ftmlAhzCb+mhfYiKtCtrv6kJttAYPfuJGz+k3Zv7R7KHzGMdnrC5s6Sw73NPk4gR2LXthYKko6/OKYW79HcuaZSlTjvQ5BcLNxcHmTRXNO2fa1YkEwaxRxEbvaG1FSZ+8vP5UdRVHcejYKK2D2srjvHpeJsPm08Sr4dCz1AQ6Lm40VD5f8Q1P35mhyvEncreAeOMT/zl3kt3GbvrmSam6uLnNLV0/gDleazrSsQqTuCC796Yq/ACnBxd91M+KjudjQ636qHpfFZC0Zx6EIihYNohudcMgcQusXAEND/Cs/+ng2TO1JcFA/Gz23/KLK2FKrwrBoDErC5/N9yHTIQmhPAVthVuuZ3NpisfE0C4SUix0IvIe/LihYJy+sioHOHHvWHx6Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
